# Generated by Django 3.2.8 on 2021-11-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
